---
platform: linux
inputs:
- name: stratos
- name: helm-chart-tarball
- name: image-tag
image_resource:
  type: docker-image
  source:
   repository: splatform/ci-stratos-github-release
   tag: "latest"

run:
  path: sh
  args:
    - -exc
    - |
      # Create Github release
      ROOT_DIR=${PWD}
      VERSION=$(cat image-tag/v2-version)
      FULL_VERSION=$(cat image-tag/v2-alpha-tag) 

      # Check tagged release version is consistent with package.json version
      TAG_RELEASE_VERSION=$(echo ${FULL_VERSION} | cut -d"-" -f1)
      if [ "${TAG_RELEASE_VERSION}" != "${VERSION}" ]; then
        echo "Package.json version is not consistent with tag release version! ${TAG_RELEASE_VERSION} != ${VERSION}"
        exit 1
      fi
      cd ${ROOT_DIR}/stratos
      GIT_TAG="$(git describe $(git rev-list --tags --max-count=1))"
      cd ${ROOT_DIR}/helm-chart-tarball
      CHART_PACKAGE=$(ls *.tgz)

      # Check that the release exists
      set +e
      github-release info -t ${VERSION}
      RETVAL=$?
      set -e

      # Delete the release if it already exists
      if [ $RETVAL -eq 0 ]; then
        github-release delete -t ${VERSION}
      fi

      # Create new release
      github-release release -t ${VERSION} --name "Stratos ${VERSION} Preview release" --pre-release

      # Upload Helm chart to release
      github-release upload -t ${VERSION} --file ${CHART_PACKAGE} --name "${CHART_PACKAGE}"
      
